name: resume-stack

services:
  frontend:
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  temporal-worker:
    volumes:
      - ./temporal:/app
    command: ["python", "-m", "src.worker"]

  backend:
    volumes:
      - ./backend/src:/app/src
      - ./backend/pom.xml:/app/pom.xml
    command: ["mvn", "-q", "spring-boot:run"]

  frontend-angular:
    volumes:
      - ./frontend-angular:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
