/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CandidateAuthRouteImport } from './routes/_candidateAuth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as CandidateSignupRouteImport } from './routes/candidate/signup'
import { Route as CandidateAuthApplyIndexRouteImport } from './routes/_candidateAuth/apply/index'
import { Route as AuthenticatedJobsIndexRouteImport } from './routes/_authenticated/jobs/index'
import { Route as AuthenticatedCandidatesIndexRouteImport } from './routes/_authenticated/candidates/index'
import { Route as AuthenticatedCandidatesUploadRouteImport } from './routes/_authenticated/candidates/upload'
import { Route as AuthenticatedCandidatesIdRouteImport } from './routes/_authenticated/candidates/$id'
import { Route as AuthenticatedEntitiesEntityTypeIndexRouteImport } from './routes/_authenticated/entities/$entityType/index'
import { Route as AuthenticatedEntitiesEntityTypeIdRouteImport } from './routes/_authenticated/entities/$entityType/$id'
import { Route as AuthenticatedCandidatesRangeMinMaxRouteImport } from './routes/_authenticated/candidates/range/$min/$max'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateAuthRoute = CandidateAuthRouteImport.update({
  id: '/_candidateAuth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const CandidateSignupRoute = CandidateSignupRouteImport.update({
  id: '/candidate/signup',
  path: '/candidate/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateAuthApplyIndexRoute = CandidateAuthApplyIndexRouteImport.update({
  id: '/apply/',
  path: '/apply/',
  getParentRoute: () => CandidateAuthRoute,
} as any)
const AuthenticatedJobsIndexRoute = AuthenticatedJobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCandidatesIndexRoute =
  AuthenticatedCandidatesIndexRouteImport.update({
    id: '/candidates/',
    path: '/candidates/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCandidatesUploadRoute =
  AuthenticatedCandidatesUploadRouteImport.update({
    id: '/candidates/upload',
    path: '/candidates/upload',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCandidatesIdRoute =
  AuthenticatedCandidatesIdRouteImport.update({
    id: '/candidates/$id',
    path: '/candidates/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEntitiesEntityTypeIndexRoute =
  AuthenticatedEntitiesEntityTypeIndexRouteImport.update({
    id: '/entities/$entityType/',
    path: '/entities/$entityType/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEntitiesEntityTypeIdRoute =
  AuthenticatedEntitiesEntityTypeIdRouteImport.update({
    id: '/entities/$entityType/$id',
    path: '/entities/$entityType/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCandidatesRangeMinMaxRoute =
  AuthenticatedCandidatesRangeMinMaxRouteImport.update({
    id: '/candidates/range/$min/$max',
    path: '/candidates/range/$min/$max',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/candidate/signup': typeof CandidateSignupRoute
  '/': typeof AuthenticatedIndexRoute
  '/candidates/$id': typeof AuthenticatedCandidatesIdRoute
  '/candidates/upload': typeof AuthenticatedCandidatesUploadRoute
  '/candidates': typeof AuthenticatedCandidatesIndexRoute
  '/jobs': typeof AuthenticatedJobsIndexRoute
  '/apply': typeof CandidateAuthApplyIndexRoute
  '/entities/$entityType/$id': typeof AuthenticatedEntitiesEntityTypeIdRoute
  '/entities/$entityType': typeof AuthenticatedEntitiesEntityTypeIndexRoute
  '/candidates/range/$min/$max': typeof AuthenticatedCandidatesRangeMinMaxRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/candidate/signup': typeof CandidateSignupRoute
  '/': typeof AuthenticatedIndexRoute
  '/candidates/$id': typeof AuthenticatedCandidatesIdRoute
  '/candidates/upload': typeof AuthenticatedCandidatesUploadRoute
  '/candidates': typeof AuthenticatedCandidatesIndexRoute
  '/jobs': typeof AuthenticatedJobsIndexRoute
  '/apply': typeof CandidateAuthApplyIndexRoute
  '/entities/$entityType/$id': typeof AuthenticatedEntitiesEntityTypeIdRoute
  '/entities/$entityType': typeof AuthenticatedEntitiesEntityTypeIndexRoute
  '/candidates/range/$min/$max': typeof AuthenticatedCandidatesRangeMinMaxRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_candidateAuth': typeof CandidateAuthRouteWithChildren
  '/login': typeof LoginRoute
  '/candidate/signup': typeof CandidateSignupRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/candidates/$id': typeof AuthenticatedCandidatesIdRoute
  '/_authenticated/candidates/upload': typeof AuthenticatedCandidatesUploadRoute
  '/_authenticated/candidates/': typeof AuthenticatedCandidatesIndexRoute
  '/_authenticated/jobs/': typeof AuthenticatedJobsIndexRoute
  '/_candidateAuth/apply/': typeof CandidateAuthApplyIndexRoute
  '/_authenticated/entities/$entityType/$id': typeof AuthenticatedEntitiesEntityTypeIdRoute
  '/_authenticated/entities/$entityType/': typeof AuthenticatedEntitiesEntityTypeIndexRoute
  '/_authenticated/candidates/range/$min/$max': typeof AuthenticatedCandidatesRangeMinMaxRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/candidate/signup'
    | '/'
    | '/candidates/$id'
    | '/candidates/upload'
    | '/candidates'
    | '/jobs'
    | '/apply'
    | '/entities/$entityType/$id'
    | '/entities/$entityType'
    | '/candidates/range/$min/$max'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/candidate/signup'
    | '/'
    | '/candidates/$id'
    | '/candidates/upload'
    | '/candidates'
    | '/jobs'
    | '/apply'
    | '/entities/$entityType/$id'
    | '/entities/$entityType'
    | '/candidates/range/$min/$max'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_candidateAuth'
    | '/login'
    | '/candidate/signup'
    | '/_authenticated/'
    | '/_authenticated/candidates/$id'
    | '/_authenticated/candidates/upload'
    | '/_authenticated/candidates/'
    | '/_authenticated/jobs/'
    | '/_candidateAuth/apply/'
    | '/_authenticated/entities/$entityType/$id'
    | '/_authenticated/entities/$entityType/'
    | '/_authenticated/candidates/range/$min/$max'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CandidateAuthRoute: typeof CandidateAuthRouteWithChildren
  LoginRoute: typeof LoginRoute
  CandidateSignupRoute: typeof CandidateSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_candidateAuth': {
      id: '/_candidateAuth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof CandidateAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/candidate/signup': {
      id: '/candidate/signup'
      path: '/candidate/signup'
      fullPath: '/candidate/signup'
      preLoaderRoute: typeof CandidateSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_candidateAuth/apply/': {
      id: '/_candidateAuth/apply/'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof CandidateAuthApplyIndexRouteImport
      parentRoute: typeof CandidateAuthRoute
    }
    '/_authenticated/jobs/': {
      id: '/_authenticated/jobs/'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof AuthenticatedJobsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/candidates/': {
      id: '/_authenticated/candidates/'
      path: '/candidates'
      fullPath: '/candidates'
      preLoaderRoute: typeof AuthenticatedCandidatesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/candidates/upload': {
      id: '/_authenticated/candidates/upload'
      path: '/candidates/upload'
      fullPath: '/candidates/upload'
      preLoaderRoute: typeof AuthenticatedCandidatesUploadRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/candidates/$id': {
      id: '/_authenticated/candidates/$id'
      path: '/candidates/$id'
      fullPath: '/candidates/$id'
      preLoaderRoute: typeof AuthenticatedCandidatesIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/entities/$entityType/': {
      id: '/_authenticated/entities/$entityType/'
      path: '/entities/$entityType'
      fullPath: '/entities/$entityType'
      preLoaderRoute: typeof AuthenticatedEntitiesEntityTypeIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/entities/$entityType/$id': {
      id: '/_authenticated/entities/$entityType/$id'
      path: '/entities/$entityType/$id'
      fullPath: '/entities/$entityType/$id'
      preLoaderRoute: typeof AuthenticatedEntitiesEntityTypeIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/candidates/range/$min/$max': {
      id: '/_authenticated/candidates/range/$min/$max'
      path: '/candidates/range/$min/$max'
      fullPath: '/candidates/range/$min/$max'
      preLoaderRoute: typeof AuthenticatedCandidatesRangeMinMaxRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedCandidatesIdRoute: typeof AuthenticatedCandidatesIdRoute
  AuthenticatedCandidatesUploadRoute: typeof AuthenticatedCandidatesUploadRoute
  AuthenticatedCandidatesIndexRoute: typeof AuthenticatedCandidatesIndexRoute
  AuthenticatedJobsIndexRoute: typeof AuthenticatedJobsIndexRoute
  AuthenticatedEntitiesEntityTypeIdRoute: typeof AuthenticatedEntitiesEntityTypeIdRoute
  AuthenticatedEntitiesEntityTypeIndexRoute: typeof AuthenticatedEntitiesEntityTypeIndexRoute
  AuthenticatedCandidatesRangeMinMaxRoute: typeof AuthenticatedCandidatesRangeMinMaxRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedCandidatesIdRoute: AuthenticatedCandidatesIdRoute,
  AuthenticatedCandidatesUploadRoute: AuthenticatedCandidatesUploadRoute,
  AuthenticatedCandidatesIndexRoute: AuthenticatedCandidatesIndexRoute,
  AuthenticatedJobsIndexRoute: AuthenticatedJobsIndexRoute,
  AuthenticatedEntitiesEntityTypeIdRoute:
    AuthenticatedEntitiesEntityTypeIdRoute,
  AuthenticatedEntitiesEntityTypeIndexRoute:
    AuthenticatedEntitiesEntityTypeIndexRoute,
  AuthenticatedCandidatesRangeMinMaxRoute:
    AuthenticatedCandidatesRangeMinMaxRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface CandidateAuthRouteChildren {
  CandidateAuthApplyIndexRoute: typeof CandidateAuthApplyIndexRoute
}

const CandidateAuthRouteChildren: CandidateAuthRouteChildren = {
  CandidateAuthApplyIndexRoute: CandidateAuthApplyIndexRoute,
}

const CandidateAuthRouteWithChildren = CandidateAuthRoute._addFileChildren(
  CandidateAuthRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CandidateAuthRoute: CandidateAuthRouteWithChildren,
  LoginRoute: LoginRoute,
  CandidateSignupRoute: CandidateSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
