/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CandidatesIndexRouteImport } from './routes/candidates/index'
import { Route as CandidatesUploadRouteImport } from './routes/candidates/upload'
import { Route as CandidatesIdRouteImport } from './routes/candidates/$id'
import { Route as EntitiesEntityTypeIndexRouteImport } from './routes/entities/$entityType/index'
import { Route as EntitiesEntityTypeIdRouteImport } from './routes/entities/$entityType/$id'
import { Route as CandidatesRangeMinMaxRouteImport } from './routes/candidates/range/$min/$max'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatesIndexRoute = CandidatesIndexRouteImport.update({
  id: '/candidates/',
  path: '/candidates/',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatesUploadRoute = CandidatesUploadRouteImport.update({
  id: '/candidates/upload',
  path: '/candidates/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatesIdRoute = CandidatesIdRouteImport.update({
  id: '/candidates/$id',
  path: '/candidates/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EntitiesEntityTypeIndexRoute = EntitiesEntityTypeIndexRouteImport.update({
  id: '/entities/$entityType/',
  path: '/entities/$entityType/',
  getParentRoute: () => rootRouteImport,
} as any)
const EntitiesEntityTypeIdRoute = EntitiesEntityTypeIdRouteImport.update({
  id: '/entities/$entityType/$id',
  path: '/entities/$entityType/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatesRangeMinMaxRoute = CandidatesRangeMinMaxRouteImport.update({
  id: '/candidates/range/$min/$max',
  path: '/candidates/range/$min/$max',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/candidates/$id': typeof CandidatesIdRoute
  '/candidates/upload': typeof CandidatesUploadRoute
  '/candidates': typeof CandidatesIndexRoute
  '/entities/$entityType/$id': typeof EntitiesEntityTypeIdRoute
  '/entities/$entityType': typeof EntitiesEntityTypeIndexRoute
  '/candidates/range/$min/$max': typeof CandidatesRangeMinMaxRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/candidates/$id': typeof CandidatesIdRoute
  '/candidates/upload': typeof CandidatesUploadRoute
  '/candidates': typeof CandidatesIndexRoute
  '/entities/$entityType/$id': typeof EntitiesEntityTypeIdRoute
  '/entities/$entityType': typeof EntitiesEntityTypeIndexRoute
  '/candidates/range/$min/$max': typeof CandidatesRangeMinMaxRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/candidates/$id': typeof CandidatesIdRoute
  '/candidates/upload': typeof CandidatesUploadRoute
  '/candidates/': typeof CandidatesIndexRoute
  '/entities/$entityType/$id': typeof EntitiesEntityTypeIdRoute
  '/entities/$entityType/': typeof EntitiesEntityTypeIndexRoute
  '/candidates/range/$min/$max': typeof CandidatesRangeMinMaxRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/candidates/$id'
    | '/candidates/upload'
    | '/candidates'
    | '/entities/$entityType/$id'
    | '/entities/$entityType'
    | '/candidates/range/$min/$max'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/candidates/$id'
    | '/candidates/upload'
    | '/candidates'
    | '/entities/$entityType/$id'
    | '/entities/$entityType'
    | '/candidates/range/$min/$max'
  id:
    | '__root__'
    | '/'
    | '/candidates/$id'
    | '/candidates/upload'
    | '/candidates/'
    | '/entities/$entityType/$id'
    | '/entities/$entityType/'
    | '/candidates/range/$min/$max'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CandidatesIdRoute: typeof CandidatesIdRoute
  CandidatesUploadRoute: typeof CandidatesUploadRoute
  CandidatesIndexRoute: typeof CandidatesIndexRoute
  EntitiesEntityTypeIdRoute: typeof EntitiesEntityTypeIdRoute
  EntitiesEntityTypeIndexRoute: typeof EntitiesEntityTypeIndexRoute
  CandidatesRangeMinMaxRoute: typeof CandidatesRangeMinMaxRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidates/': {
      id: '/candidates/'
      path: '/candidates'
      fullPath: '/candidates'
      preLoaderRoute: typeof CandidatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidates/upload': {
      id: '/candidates/upload'
      path: '/candidates/upload'
      fullPath: '/candidates/upload'
      preLoaderRoute: typeof CandidatesUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidates/$id': {
      id: '/candidates/$id'
      path: '/candidates/$id'
      fullPath: '/candidates/$id'
      preLoaderRoute: typeof CandidatesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entities/$entityType/': {
      id: '/entities/$entityType/'
      path: '/entities/$entityType'
      fullPath: '/entities/$entityType'
      preLoaderRoute: typeof EntitiesEntityTypeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entities/$entityType/$id': {
      id: '/entities/$entityType/$id'
      path: '/entities/$entityType/$id'
      fullPath: '/entities/$entityType/$id'
      preLoaderRoute: typeof EntitiesEntityTypeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidates/range/$min/$max': {
      id: '/candidates/range/$min/$max'
      path: '/candidates/range/$min/$max'
      fullPath: '/candidates/range/$min/$max'
      preLoaderRoute: typeof CandidatesRangeMinMaxRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CandidatesIdRoute: CandidatesIdRoute,
  CandidatesUploadRoute: CandidatesUploadRoute,
  CandidatesIndexRoute: CandidatesIndexRoute,
  EntitiesEntityTypeIdRoute: EntitiesEntityTypeIdRoute,
  EntitiesEntityTypeIndexRoute: EntitiesEntityTypeIndexRoute,
  CandidatesRangeMinMaxRoute: CandidatesRangeMinMaxRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
