/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CandidatesUploadRouteImport } from './routes/candidates/upload'
import { Route as CandidatesIdRouteImport } from './routes/candidates/$id'
import { Route as EntitiesEntityTypeIndexRouteImport } from './routes/entities/$entityType/index'
import { Route as EntitiesEntityTypeIdRouteImport } from './routes/entities/$entityType/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatesUploadRoute = CandidatesUploadRouteImport.update({
  id: '/candidates/upload',
  path: '/candidates/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatesIdRoute = CandidatesIdRouteImport.update({
  id: '/candidates/$id',
  path: '/candidates/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EntitiesEntityTypeIndexRoute = EntitiesEntityTypeIndexRouteImport.update({
  id: '/entities/$entityType/',
  path: '/entities/$entityType/',
  getParentRoute: () => rootRouteImport,
} as any)
const EntitiesEntityTypeIdRoute = EntitiesEntityTypeIdRouteImport.update({
  id: '/entities/$entityType/$id',
  path: '/entities/$entityType/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/candidates/$id': typeof CandidatesIdRoute
  '/candidates/upload': typeof CandidatesUploadRoute
  '/entities/$entityType/$id': typeof EntitiesEntityTypeIdRoute
  '/entities/$entityType': typeof EntitiesEntityTypeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/candidates/$id': typeof CandidatesIdRoute
  '/candidates/upload': typeof CandidatesUploadRoute
  '/entities/$entityType/$id': typeof EntitiesEntityTypeIdRoute
  '/entities/$entityType': typeof EntitiesEntityTypeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/candidates/$id': typeof CandidatesIdRoute
  '/candidates/upload': typeof CandidatesUploadRoute
  '/entities/$entityType/$id': typeof EntitiesEntityTypeIdRoute
  '/entities/$entityType/': typeof EntitiesEntityTypeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/candidates/$id'
    | '/candidates/upload'
    | '/entities/$entityType/$id'
    | '/entities/$entityType'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/candidates/$id'
    | '/candidates/upload'
    | '/entities/$entityType/$id'
    | '/entities/$entityType'
  id:
    | '__root__'
    | '/'
    | '/candidates/$id'
    | '/candidates/upload'
    | '/entities/$entityType/$id'
    | '/entities/$entityType/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CandidatesIdRoute: typeof CandidatesIdRoute
  CandidatesUploadRoute: typeof CandidatesUploadRoute
  EntitiesEntityTypeIdRoute: typeof EntitiesEntityTypeIdRoute
  EntitiesEntityTypeIndexRoute: typeof EntitiesEntityTypeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidates/upload': {
      id: '/candidates/upload'
      path: '/candidates/upload'
      fullPath: '/candidates/upload'
      preLoaderRoute: typeof CandidatesUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidates/$id': {
      id: '/candidates/$id'
      path: '/candidates/$id'
      fullPath: '/candidates/$id'
      preLoaderRoute: typeof CandidatesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entities/$entityType/': {
      id: '/entities/$entityType/'
      path: '/entities/$entityType'
      fullPath: '/entities/$entityType'
      preLoaderRoute: typeof EntitiesEntityTypeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entities/$entityType/$id': {
      id: '/entities/$entityType/$id'
      path: '/entities/$entityType/$id'
      fullPath: '/entities/$entityType/$id'
      preLoaderRoute: typeof EntitiesEntityTypeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CandidatesIdRoute: CandidatesIdRoute,
  CandidatesUploadRoute: CandidatesUploadRoute,
  EntitiesEntityTypeIdRoute: EntitiesEntityTypeIdRoute,
  EntitiesEntityTypeIndexRoute: EntitiesEntityTypeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
